version: '3.4'

services:
  bulkybookweb:
    image: ${DOCKER_REGISTRY-}bulkybookweb
    build:
      context: .
      dockerfile: BulkyWeb/Dockerfile
    ports:
      - "32768:8080"
    depends_on:
      - mssql

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-preview-ubuntu-22.04
    environment:
      SA_PASSWORD: Password*
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"