apiVersion: apps/v1
kind: Deployment
metadata:
  name: bulkybookweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bulkybookweb
  template:
    metadata:
      labels:
        app: bulkybookweb
    spec:
      containers:
      - name: bulkybookweb
        image: iskrenvanev/bulky:dev
        ports:
        - containerPort: 8081